In [8]:
import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print("Week 1 Temperatures (°C):", temperatures_w1)

Week 1 Temperatures (°C): [22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [9]:
print("Shape:", temperatures_w1.shape)
print("Data type:", temperatures_w1.dtype)
print("Number of elements:", temperatures_w1.size)

Shape: (7,)
Data type: float64
Number of elements: 7


In [10]:
temperatures_fahrenheit = (temperatures_w1 * 9/5) + 32
print("Temperatures in Fahrenheit:", temperatures_fahrenheit)

Temperatures in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [11]:
print("Maximum Temperature:", np.max(temperatures_w1))
print("Minimum Temperature:", np.min(temperatures_w1))
print("Mean Temperature:", np.mean(temperatures_w1))

Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.542857142857144


In [12]:
print("First 3 Days Temperatures:", temperatures_w1[:3])

First 3 Days Temperatures: [22.5 25.3 20.8]


In [13]:
print("Weekend Temperatures:", temperatures_w1[-2:])
print("Middle 3 Days Temperatures:", temperatures_w1[2:5])

Weekend Temperatures: [24.8 21.9]
Middle 3 Days Temperatures: [20.8 23.4 26.1]


In [14]:
temperatures_w2 = np.array([19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1])
temperatures = np.array([temperatures_w1, temperatures_w2])
print("2D Array of Temperatures:\n", temperatures)

2D Array of Temperatures:
 [[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [15]:
print("Shape:", temperatures.shape)
print("Data type:", temperatures.dtype)
print("Number of elements:", temperatures.size)

Shape: (2, 7)
Data type: float64
Number of elements: 14


In [16]:
print("Week 1 Temperatures:", temperatures[0])
print("Week 2 Temperatures:", temperatures[1])
print("Weekend Temperatures (Both Weeks):\n", temperatures[:, -2:])

Week 1 Temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2 Temperatures: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Weekend Temperatures (Both Weeks):
 [[24.8 21.9]
 [22.8 20.1]]


In [18]:
import pandas as pd

marks = pd.Series([95, 92, 89, 85, 80], index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
print("Marks Series:\n", marks)

Marks Series:
 Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [22]:
print("1st Rank (by integer index):", marks.iloc[0])

1st Rank (by integer index): 95


In [23]:
print("Top 3 Ranks (by label):\n", marks.loc[['Rank1', 'Rank2', 'Rank3']])

Top 3 Ranks (by label):
 Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [24]:
print("3rd Rank (by iloc):", marks.iloc[2])


3rd Rank (by iloc): 89


In [25]:
print("Ranks with marks > 90:\n", marks[marks > 90])

Ranks with marks > 90:
 Rank1    95
Rank2    92
dtype: int64


In [26]:
marks['Rank1'] = 100
print("After modifying Rank1:\n", marks)

After modifying Rank1:
 Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [27]:
marks = marks.drop('Rank5')
print("After removing Rank5:\n", marks)

After removing Rank5:
 Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [28]:
cgpa = marks / 10
print("CGPA Series:\n", cgpa)

CGPA Series:
 Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [29]:
import pandas as pd

data = {
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
                        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}

transactions = pd.DataFrame(data)
print("Transactions DataFrame:\n", transactions)

Transactions DataFrame:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [30]:
print("Head:\n", transactions.head())
print("\nTail:\n", transactions.tail())
print("\nShape:", transactions.shape)
print("\nColumns:", transactions.columns.tolist())
print("\nData Types:\n", transactions.dtypes)

Head:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Tail:
    TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Shape: (10, 4)

Columns: ['TransactionID', 'ProductCategory', 'Region', 'Amount']

Data Types:
 TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [31]:
print(transactions[['ProductCategory', 'Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [32]:
print("Last 3 columns:\n", transactions.iloc[:, -3:])

Last 3 columns:
   ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [33]:
north_high = transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]
print("North Region with Amount > 200:\n", north_high)

North Region with Amount > 200:
    TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [34]:
print("Product Category Counts:\n", transactions['ProductCategory'].value_counts())

Product Category Counts:
 ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [35]:
print("Unique Regions:", transactions['Region'].unique())

Unique Regions: ['North' 'South' 'East' 'West']


In [36]:
region_mean = transactions.groupby('Region')['Amount'].mean()
print("Mean Amount by Region:\n", region_mean)

Mean Amount by Region:
 Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [37]:
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
print("Updated Transaction 102:\n", transactions[transactions['TransactionID'] == 102])

Updated Transaction 102:
    TransactionID ProductCategory Region  Amount
1            102        Clothing  South     165


In [38]:
transactions['Discount'] = transactions['Amount'] * 0.10
print("With Discount Column:\n", transactions.head())

With Discount Column:
    TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0


In [39]:
transactions = transactions[transactions['TransactionID'] != 109]
print("After Removing Transaction 109:\n", transactions)

After Removing Transaction 109:
    TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [40]:
transactions = transactions.drop(columns='Discount')
print("After Dropping Discount Column:\n", transactions)

After Dropping Discount Column:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
